create table public.categoria (
       cat_id int8 generated by default as identity,
        cat_nome varchar(20) not null,
        primary key (cat_id)
    );

INSERT INTO public.categoria (cat_nome) values ('Lazer');
INSERT INTO public.categoria (cat_nome) values ('Alimentação');
INSERT INTO public.categoria (cat_nome) values ('Supermercado');
INSERT INTO public.categoria (cat_nome) values ('Farmácia');
INSERT INTO public.categoria (cat_nome) values ('Outros');
